version: "3.0"
services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mariadb_container
        ports:
            - "3306:3306"
        networks:
            - my_network
        env_file:
            - .env
        volumes:
            - ${VOLUME_PATH}/mariadb_data:/var/lib/mysql

    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress_container
        ports:
            - "9000:9000"
        networks:
            - my_network
        env_file:
            - .env
        volumes:
            - ${VOLUME_PATH}/wp_data:/var/www/html
        depends_on:
            - mariadb

    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx_container
        ports:
            - "443:443"
        networks:
            - my_network
        env_file:
            - .env
        volumes:
            - ${VOLUME_PATH}/wp_data:/var/www/html
        depends_on:
            - wordpress

networks:
    my_network:
        driver: bridge
